version: '3'

services:
  db:
    image: postgres
    container_name: xyinc_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=xy_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d
  app:
    image: app-image
    container_name: xyinc_app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db      
    volumes:
      - /data/spring-app
